#!/bin/bash
# Define color codes



echo "TEST"
echo ""

url="./data"
disk=$(cat $url/disk)
efi=$(cat $url/efi)
root=$(cat $url/root)
home=$(cat $url/home)
efi_size_mb=$(cat $url/efi_size)
root_size_gb=$(cat $url/root_size)
intero=$(lsblk -l | awk '$1=="sda3"{print $4}' | sed 's/.$//')
diff=$(echo "$intero - $root_size_gb" | bc)

p1="/dev/$efi"
p2="/dev/$root"
p3="/dev/$home"

echo "$p1 $efi_size_mb"
echo "$p2 $root_size_gb"
echo "$p3 $diff"

country=$(cat $url/country)
localhost=$(cat $url/localhost)
username=$(cat $url/username)
realname=$(cat $url/realname)
rootpw=$(cat $url/rootpw)
userpw=$(cat $url/userpw)
localegen=$(cat $url/localegen)
localeconf=$(cat $url/localeconf)
keymap=$(cat $url/keymap)
localtime=$(cat $url/localtime)
zram=$(cat $url/zram)





echo ""


echo "Country: $country"
echo "Localhost: $localhost"
echo "Username: $username"
echo "realname: $realname"
echo "root password: $rootpw"
echo "user password: $userpw"
echo "localegen: $localegen"
echo "localeconf: $localeconf"
echo "keymap: $keymap"
echo "localtime: $localtime"
echo "zram[swap]: $zram GiB"

echo ""



read -p $'\033[0;31m'"Warning: If you accept to continue, the entire disk will be partitioned and all data will be lost. Continue? [y/n] "$'\033[0m' choice

case "$choice" in
  y|Y )
    # Inserire qui il codice da eseguire se si sceglie di continuare
    echo "Beginning core installation.."
    ;;
  n|N )
    # Inserire qui il codice da eseguire se si sceglie di abortire
    echo "Operation cancelled.."
    exit
    ;;
  * )
    echo "Invalid choice!"
    exit 1
    ;;
esac
